<?php
class LeaveForm extends \yii\base\Model{
    public $time;
    public $start_t;
    public $end_t;
    public $reason;
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}